# Generated by Django 5.2.3 on 2025-07-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('penalty_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('personnel_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
