# Generated by Django 5.2.4 on 2025-07-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('academic_record_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('graduation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Academic Background',
                'verbose_name_plural': 'Academic Backgrounds',
                'db_table': '"member"."academic_background"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=255)),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
                ('permission', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Admin Account',
                'verbose_name_plural': 'Admin Accounts',
                'db_table': '"admin"."admin_account"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AwardsRecognition',
            fields=[
                ('award_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Award/Recognition',
                'verbose_name_plural': 'Awards & Recognitions',
                'db_table': '"member"."awards_recognition"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('penalty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
            ],
            options={
                'verbose_name': 'Disciplinary Action',
                'verbose_name_plural': 'Disciplinary Actions',
                'db_table': '"member"."disciplinary_action"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyDetail',
            fields=[
                ('family_member_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('blessing', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Family Detail',
                'verbose_name_plural': 'Family Details',
                'db_table': '"member"."family_detail"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicMissionPost',
            fields=[
                ('mission_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('final_position', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Public Mission Post',
                'verbose_name_plural': 'Public Mission Posts',
                'db_table': '"member"."public_mission_post"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qualification_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_acquisition', models.CharField(blank=True, max_length=50, null=True)),
                ('name_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'db_table': '"member"."qualification"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialNote',
            fields=[
                ('note_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_written', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Special Note',
                'verbose_name_plural': 'Special Notes',
                'db_table': '"member"."special_note"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('training_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_course', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Training Course',
                'verbose_name_plural': 'Training Courses',
                'db_table': '"member"."training_course"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('experience_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('final_position', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'db_table': '"member"."work_experience"',
                'managed': False,
            },
        ),
    ]
