# Generated by Django 5.2.3 on 2025-07-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_in', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('ip_address', models.CharField(max_length=100)),
            ],
        ),
    ]
