# Generated by Django 5.2.3 on 2025-07-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('academic_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('personnel_id', models.IntegerField()),
                ('period', models.CharField(max_length=100)),
                ('school_university', models.CharField(max_length=255)),
                ('major_degree', models.CharField(max_length=255)),
                ('graduation', models.CharField(max_length=100)),
            ],
        ),
    ]
