# Generated by Django 5.2.3 on 2025-06-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('academic_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=255)),
                ('school_university', models.CharField(max_length=255)),
                ('major_degree', models.CharField(max_length=255)),
                ('graduation', models.CharField(max_length=255)),
                ('personnel_id', models.IntegerField()),
            ],
        ),
    ]
