# Generated by Django 5.2.3 on 2025-07-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('access_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('personnel_id', models.CharField(max_length=100)),
                ('role_type', models.CharField(max_length=100)),
                ('date_assigned', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
