# Generated by Django 5.2.3 on 2025-06-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('award_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('organization', models.CharField(max_length=255)),
                ('personnel_id', models.IntegerField()),
            ],
        ),
    ]
